version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      target: server
    ports:
      - "8000:8000" # Expose the FastAPI server on port 8000
    restart: unless-stopped # Restart the service unless it is stopped manually

  gradio_app:
    build:
      context: ./client
      target: client
    ports:
      - "7860:7860"
    depends_on:
      - fastapi_app
    restart: unless-stopped
    # command: tail -f /dev/null # Keeps the container running without executing app.py
